# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "054f3c25ce9f9ed29c70fba2235ffef2"
application_url = "https://anxiety-readily-dirt-relaxation.trycloudflare.com"
embedded = true
name = "wishlist-wo"
handle = "wishlist-wo"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "clotho-verse.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://anxiety-readily-dirt-relaxation.trycloudflare.com/auth/callback",
  "https://anxiety-readily-dirt-relaxation.trycloudflare.com/auth/shopify/callback",
  "https://anxiety-readily-dirt-relaxation.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
